package enums
{
	
	/**
	 * Item type id enum.
	 * 
	 * @author Relena
	 */
	public class ItemTypeIdEnum
	{
		public static const AMULET:int = 1;
		public static const BOW:int = 2;
		public static const WAND:int = 3;
		public static const STAFF:int = 4;
		public static const DAGGER:int = 5;
		public static const SWORD:int = 6;
		public static const HAMMER:int = 7;
		public static const SHOVEL:int = 8;
		public static const RING:int = 9;
		public static const BELT:int = 10;
		public static const BOOTS:int = 11;
		public static const POTION:int = 12;
		public static const EXPERIENCE_SCROLL:int = 13;
		public static const ORDER_ABILITY_ITEM:int = 14;
		public static const MISCELLANEOUS:int = 15;
		public static const HAT:int = 16;
		public static const CLOAK:int = 17;
		public static const PET:int = 18;
		public static const AXE:int = 19;
		public static const TOOL:int = 20;
		public static const PICKAXE:int = 21;
		public static const SCYTHE:int = 22;
		public static const DOFUS:int = 23;
		public static const MISCELLANEOUS_2:int = 24;
		public static const DOCUMENT:int = 25;
		public static const SMITHMAGIC_POTION:int = 26;
		public static const MUTATION_ITEM:int = 27;
		public static const BOOST_FOOD:int = 28;
		public static const BLESSING:int = 29;
		public static const CURSE:int = 30;
		public static const ROLEPLAY_BUFF:int = 31;
		public static const FOLLOWING_CHARACTER:int = 32;
		public static const BREAD:int = 33;
		public static const CEREAL:int = 34;
		public static const FLOWER:int = 35;
		public static const PLANT:int = 36;
		public static const BEER:int = 37;
		public static const WOOD:int = 38;
		public static const ORE:int = 39;
		public static const ALLOY:int = 40;
		public static const FISH:int = 41;
		public static const TREAT:int = 42;
		public static const SPELL_DELEVELING_POTION:int = 43;
		public static const PROFESSION_DELEVELING_POTION:int = 44;
		public static const WEAPON_SKILL_DELEVELING_POTION:int = 45;
		public static const FRUIT:int = 46;
		public static const BONE:int = 47;
		public static const POWDER:int = 48;
		public static const EDIBLE_FISH:int = 49;
		public static const PRECIOUS_STONE:int = 50;
		public static const STONE:int = 51;
		public static const FLOUR:int = 52;
		public static const FEATHER:int = 53;
		public static const HAIR:int = 54;
		public static const FABRIC:int = 55;
		public static const LEATHER:int = 56;
		public static const WOOL:int = 57;
		public static const SEED:int = 58;
		public static const SKIN:int = 59;
		public static const OIL:int = 60;
		public static const STUFFED_TOY:int = 61;
		public static const GUTTED_FISH:int = 62;
		public static const MEAT:int = 63;
		public static const PRESERVED_MEAT:int = 64;
		public static const TAIL:int = 65;
		public static const METARIA:int = 66;
		public static const VEGETABLE:int = 68;
		public static const EDIBLE_MEAT:int = 69;
		public static const DYE:int = 70;
		public static const ALCHEMY_EQUIPMENT:int = 71;
		public static const PET_EGG:int = 72;
		public static const SKILL:int = 73;
		public static const FAIRYWORK:int = 74;
		public static const SPELL_LEARNING_SCROLL:int = 75;
		public static const CHARACTERISTIC_SCROLL:int = 76;
		public static const PET_CERTIFICATE:int = 77;
		public static const SMITHMAGIC_RUNE:int = 78;
		public static const DRINK:int = 79;
		public static const MISSION_ITEM:int = 80;
		public static const BACKPACK:int = 81;
		public static const SHIELD:int = 82;
		public static const SOUL_STONE:int = 83;
		public static const KEY:int = 84;
		public static const FULL_SOUL_STONE:int = 85;
		public static const PERCEPTOR_DELEVELING_POTION:int = 86;
		public static const SEEKER_SCROLL:int = 87;
		public static const MAGIC_STONE:int = 88;
		public static const GIFT:int = 89;
		public static const PET_GHOST:int = 90;
		public static const DRAGOTURKEY:int = 91;
		public static const GOBBALL:int = 92;
		public static const BREEDING_ITEM:int = 93;
		public static const USABLE_ITEM:int = 94;
		public static const PLANK:int = 95;
		public static const BARK:int = 96;
		public static const MOUNT_CERTIFICATE:int = 97;
		public static const ROOT:int = 98;
		public static const CAPTURING_NET:int = 99;
		public static const BAG_OF_RESOURCES:int = 100;
		public static const CROSSBOW:int = 102;
		public static const LEG:int = 103;
		public static const WING:int = 104;
		public static const EGG:int = 105;
		public static const EAR:int = 106;
		public static const CARAPACE:int = 107;
		public static const BUD:int = 108;
		public static const EYE:int = 109;
		public static const JELLY:int = 110;
		public static const SHELL:int = 111;
		public static const PRISM:int = 112;
		public static const LIVING_OBJECT:int = 113;
		public static const MAGIC_WEAPON:int = 114;
		public static const FRAGMENT_OF_SHUSHU_SOUL:int = 115;
		public static const PET_POTION:int = 116;
		public static const EQUIPMENT:int = 118;
		public static const MUSHROOM:int = 119;
		public static const PETSMOUNT:int = 121;
		public static const PETSMOUNT_POTION:int = 122;
		public static const PETSMOUNT_CERTIFICATE:int = 123;
		public static const PETSMOUNT_GHOST:int = 124;
		public static const SOUVENIR:int = 125;
		public static const MAIN_QUESTS:int = 126;
		public static const TEMPLE_QUESTS:int = 127;
		public static const WANTED_NOTICE:int = 128;
		public static const ALIGNMENT:int = 129;
		public static const CITY_ORDER:int = 130;
		public static const EVENT:int = 131;
		public static const ARCHIPELAGO_OF_VULKANIA:int = 132;
		public static const ASTRUB:int = 133;
		public static const CITY_QUESTS:int = 134;
		public static const BWORK_CAMP:int = 136;
		public static const CANIA:int = 137;
		public static const AMAKNA_CASTLE:int = 138;
		public static const FRIGOST_ISLAND:int = 139;
		public static const OTOMAI_ISLAND:int = 140;
		public static const KWISMAS_ISLAND:int = 141;
		public static const INCARNAM:int = 142;
		public static const KOALAK_MOUNTAIN:int = 143;
		public static const PANDALA:int = 144;
		public static const MADRESTAM_HARBOUR:int = 145;
		public static const PROVINCE_OF_AMAKNA:int = 146;
		public static const KROSMOZ:int = 147;
		public static const TOKEN:int = 148;
		public static const MOON_ISLAND:int = 149;
		public static const WABBIT_ISLAND:int = 150;
		public static const TROPHY:int = 151;
		public static const PEBBLE:int = 152;
		public static const KWISMAS:int = 153;
		public static const WRAPPING_PAPER:int = 154;
		public static const SUFOKIA:int = 155;
		public static const ALMANAX:int = 156;
		public static const FIGURINE:int = 157;
		public static const CARAMEL_RABMAJOKE:int = 158;
		public static const STRAWBERRY_RABMAJOKE:int = 159;
		public static const LEMON_RABMAJOKE:int = 160;
		public static const ORANGE_RABMAJOKE:int = 161;
		public static const KOLA_RABMAJOKE:int = 162;
		public static const NOUGAT_RABMAJOKE:int = 163;
		public static const GARMENT:int = 164;
		public static const CONQUEST_POTION:int = 165;
		
		//for (var ii:int = 1; ii < 1000; ii++){
		//	try{
		//		sysApi.log(8, "public static const " + dataApi.getItemType(ii).replace(RegExp(/ /g), "_").toLocaleUpperCase() + ":int = " + ii + ";");
		//	}catch (e:Error){}
		//}
	}
}